add array_slice op
fluencelabs/rust-peer pull request #1313
Opened 2022-09-22 02:43 UTC by boneyard93501

2022-09-22 02:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/fluencelabs/rust-peer?pullRequest=1313) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/fluencelabs/rust-peer?pullRequest=1313) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/fluencelabs/rust-peer?pullRequest=1313) it.</sub>

2022-10-31 09:44 UTC, justprosh requested changes
You should check that `start < end` otherwise it panics

2022-10-31 09:44 UTC, justprosh commented
Also add test for this case

2022-10-31 09:57 UTC, justprosh approved these changes

2022-10-31 10:17 UTC, folex commented
> Y̶o̶u̶ ̶s̶h̶o̶u̶l̶d̶ ̶c̶h̶e̶c̶k̶ ̶t̶h̶a̶t̶ ̶`̶s̶t̶a̶r̶t̶ ̶<̶ ̶e̶n̶d̶`̶ ̶o̶t̶h̶e̶r̶w̶i̶s̶e̶ ̶i̶t̶ ̶p̶a̶n̶i̶c̶s̶
> 
> UPD: it checks but there is no test for this case

there's such a check in tests 🙈

2022-10-31 12:29 UTC, kmd-fl approved these changes

2022-11-01 08:38 UTC, merged