Gather some service metrics for aliased services separately
fluencelabs/rust-peer pull request #1324
Opened 2022-09-30 17:01 UTC by kmd-fl

2022-09-30 17:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/fluencelabs/rust-peer?pullRequest=1324) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/fluencelabs/rust-peer?pullRequest=1324) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/fluencelabs/rust-peer?pullRequest=1324) it.</sub>

2022-10-04 08:53 UTC, folex commented on aquamarine/src/particle_functions.rs
> -                };
You're not using `FunctionKind::Builtin` anymore?

2022-10-04 08:54 UTC, folex commented on crates/peer-metrics/src/particle_executor.rs
> +    Function,
`FunctionKind::Function` is kinda hard to understand. What about `FunctionKind::ParticleFunction`?

2022-10-04 08:58 UTC, folex commented on particle-services/src/app_services.rs
> +        let service_type = ServiceType::Service(service.aliases.first().cloned());
Is order of aliases preserved between node restarts?

2022-10-04 09:00 UTC, folex commented on crates/peer-metrics/src/services_metrics/backend.rs
>                                  builtin_metrics.update(service_id, function_name, stats);
Do you record call stats for aliased services anywhere? If not, then why not?

2022-10-04 09:03 UTC, folex commented on aquamarine/src/particle_functions.rs
> -                };
If not, then does it make sense to have these metrics by `FunctionKindLabel` then?
```
service_call_time_sec: Family<FunctionKindLabel, Histogram>,
service_call_success: Family<FunctionKindLabel, Counter>,
service_call_failure: Family<FunctionKindLabel, Counter>,
```
Maybe stop recording these metrics, and record everything via `CallStat`/`ServicesMetricsBuiltin`?

2022-10-04 09:08 UTC, folex commented on particle-builtins/src/builtins.rs
> +    }
Nice!

2022-10-04 09:13 UTC, folex commented on particle-builtins/src/builtins.rs
> +            _                      => FunctionOutcome::NotDefined { args, params: particle },
👍

2022-10-04 09:18 UTC, folex requested changes
Everything looks good! But we also need to collect call stats for aliased services.

I think that `service_call_*` stats from `ParticleExecutorMetrics` should be merged with `CallStats` and collected for both aliased and non-aliased services in a same manner.

2022-10-04 13:57 UTC, kmd-fl commented on particle-services/src/app_services.rs
> +        let service_type = ServiceType::Service(service.aliases.first().cloned());
It seems so. Toml is responsible for de/serialization, and we don't break the order in the process. Additionally, I checked and it was fine.

2022-10-04 14:19 UTC, folex approved these changes

2022-10-04 14:21 UTC, merged