Add spell event bus
fluencelabs/rust-peer pull request #1356
Opened 2022-12-05 09:18 UTC by kmd-fl

2022-12-05 09:44 UTC, folex commented on crates/spell-event-bus/src/api.rs
> +pub struct SpellEvent {
Hmm, reads as `event produced by spell`. How about one of those: `SpellRunRequest` / `RunRequest` / `SpellCast` / `CastRequest` / `Trigger`?

I guess given all the `TriggerConfig`s, the `Trigger` would be the most suitable.

2022-12-05 09:46 UTC, folex commented on crates/spell-event-bus/src/api.rs
> +    /// Subscribe a listener with a specified ID to a list of events
```suggestion
    /// Subscribe a spell to a list of triggers
```

2022-12-05 09:47 UTC, folex commented on crates/spell-event-bus/src/api.rs
> +                "full"
How can an unbounded channel be full?

2022-12-05 09:50 UTC, folex commented on crates/spell-event-bus/src/api.rs
> +pub struct SpellEvent {
On the other hand, it's an **Event**Bus, right? So maybe `Event` is good.

2022-12-05 09:57 UTC, folex commented on crates/spell-event-bus/src/bus.rs
> +                log::error!("{}", e);
That won't do. You have to put some explanation on what happened, and why this error matters, and what it relates to.

Also, it doesn't seem like a critical error, so I would put it to `warn`. Better still, I would route that error back to the client where possible. 

Eg if `Subscribe`, `Unsubscribe` or `UpdateTriggerConfig` failed, it MUST be visible in Aqua/AIR. So such an error MUST be passed back to builtins.

2022-12-05 09:58 UTC, folex commented on crates/spell-event-bus/src/bus.rs
> +    fn notify_spell(
Event Bus _notifies_ spells about _events_ that happened according to _trigger_ config. 3 different words for the same thing.

How about this?
```suggestion
    fn trigger_spell(
```

2022-12-05 10:02 UTC, folex commented on sorcerer/src/spells.rs
> +    spell_event_bus_api.subscribe(service_id.clone(), config)?;
Will the returned error make sense to the human who calls `spell.install`? Maybe add some context for the error?

2022-12-05 10:02 UTC, folex commented on sorcerer/src/spells.rs
> +    spell_event_bus_api.unsubscribe(spell_id.clone()).await?;
ditto: context

2022-12-05 10:18 UTC, justprosh commented on crates/spell-event-bus/src/bus.rs
> +    subscribers: HashMap<PeerEventType, Vec<Arc<SpellId>>>,
Oh, it is done to avoid copying

2022-12-05 11:28 UTC, kmd-fl commented on crates/spell-event-bus/src/api.rs
> +                "full"
That's the interface [TrySendError](https://docs.rs/futures/latest/futures/channel/mpsc/struct.TrySendError.html)

2022-12-05 11:45 UTC, kmd-fl commented on crates/spell-event-bus/src/bus.rs
> +                log::error!("{}", e);
> what happened, and why this error matters, and what it relates to.

Doesn't the `log` crate add this info automatically? And errors are explained in the `thiserror::Error` impl.

`unsubscribe` right now can fail only when replying to dropped channel, so here we can't do anything else. It seems we need to add a similar channel for `subscribe` to notify about the subscription status.

2022-12-06 11:36 UTC, folex commented on crates/spell-event-bus/src/bus.rs
> +                log::error!("{}", e);
Without a prefix, it would be impossible to find the line of code that produced that log.

2022-12-06 11:37 UTC, folex commented on crates/spell-event-bus/src/bus.rs
> +                log::error!("{}", e);
> And errors are explained in the thiserror::Error impl.

Can these errors happen under different circumstances, in different places? If yes, then log must explain where this error happened and how to interpret it.

2022-12-07 13:31 UTC, kmd-fl commented on crates/spell-event-bus/src/api.rs
> +                "full"
Because you can get only one thing from this structure: an error type or content. https://docs.rs/futures/latest/futures/channel/mpsc/struct.TrySendError.html#method.into_inner

2022-12-07 13:34 UTC, kmd-fl commented on crates/spell-event-bus/src/bus.rs
> +                log::error!("{}", e);
Well, I think internal errors of the bus shouldn't be available to users, just the fact that smth that don't depend on them went wrong and they should report it. The wrong things that can happen in all these commands are all internal now. The only exception is the timer config, but it should be validated before, and it should be impossible to construct an invalid config.

2022-12-09 06:22 UTC, folex commented on crates/spell-event-bus/src/bus.rs
> +                log::error!("spell-event-bus internal error: {}", e);
Not `log::error`, but `log::warn`, please. 

`log::error` should **only** happen when there's an error that's critical to Rust Peer. Like, something really broken and rust-peer won't ever work.

2022-12-09 06:24 UTC, folex commented on crates/spell-event-bus/src/bus.rs
> +                log::error!("spell-event-bus internal error: {}", e);
```suggestion
                log::warn!("Error in spell event bus run loop: {:?}", e);
```

2022-12-09 06:31 UTC, folex commented on crates/spell-event-bus/src/bus.rs
> +                                state.subscribe(spell_id.clone(), &config).expect("invalid timer config detected while subscribing a spell");
I suggest to return `Err` instead of panic here. As I understand it, `expect` would allow anyone to pass invalid config and crash whole EventBus.

Also, this error about invalid timer should be sent back to user. 

You said before that
> The only exception is the timer config, but it should be validated before, and it should be impossible to construct an invalid config.

If this is true, then maybe express it in types? And pass validated config here, thus avoiding validation on this level.

2022-12-09 06:32 UTC, folex commented on crates/spell-event-bus/src/bus.rs
> +                        let rescheduled = Scheduled::at(scheduled_spell.data, Instant::now()).expect("invalid timer config detected while rescheduling a spell");
Same about validating config. Let's pass already-validated config and avoid validation on this level.

2022-12-09 07:14 UTC, kmd-fl commented on crates/spell-event-bus/src/bus.rs
> +                                state.subscribe(spell_id.clone(), &config).expect("invalid timer config detected while subscribing a spell");
This is happening only because we can't prove to the compiler that `now + period` won't overflow. `Instant::now() + Duration` will panic on overflow, `Instant::now().checked_add(Duration)` returns `None` on overflow.

So, by the introduced invariant, it's impossible to give an invalid config, so there's nothing to report back to the user, but it's impossible to express it in types. We can use `+`, but the function won't be total, and implicit unwrapping will be happening nevertheless.  

I believe it's better to make this panic explicit.

2022-12-09 07:16 UTC, folex commented on sorcerer/src/spells.rs
> +        log::error!("can't subscribe a spell {} to triggers {:?} via spell-event-bus-api: {}. Removing created spell service...", spell_id, config, err);
```suggestion
        log::warn!("can't subscribe a spell {} to triggers {:?} via spell-event-bus-api: {}. Removing created spell service...", spell_id, config, err);
```

2022-12-09 07:16 UTC, folex commented on sorcerer/src/spells.rs
> +            "can't install a spell due to an internal error"
Could you please return a more descriptive error? Like the log you have above.

This will be useful when someone sends us this error and asks for help.

2022-12-09 07:17 UTC, folex commented on sorcerer/src/spells.rs
> +        log::error!(
```suggestion
        log::warn!(
```

2022-12-09 07:17 UTC, folex commented on sorcerer/src/spells.rs
> +            "can't remove a spell {} due to an internal error",
More descriptive error.

2022-12-09 08:38 UTC, folex commented on crates/spell-event-bus/src/bus.rs
> +                                state.subscribe(spell_id.clone(), &config).expect("invalid timer config detected while subscribing a spell");
One option is to just do nothing on `None`.

2022-12-12 09:43 UTC, folex commented on crates/spell-event-bus/src/bus.rs
> +                                state.subscribe(spell_id.clone(), &config).unwrap_or(());
Maybe write a log?

2022-12-12 09:45 UTC, folex approved these changes

2022-12-12 09:48 UTC, justprosh requested changes
Please, add tests for connection pool events

2022-12-12 09:53 UTC, folex commented on crates/spell-event-bus/src/api.rs
> +    pub(crate) reply: OneshotOutlet<()>,
> Please, add tests for connection pool events

In the next PR. This has been hanging for 7 days already. Where have you been? :)

2022-12-12 09:57 UTC, justprosh approved these changes

2022-12-12 10:02 UTC, merged