chore: move async-std to tokio
fluencelabs/rust-peer pull request #1469
Opened 2023-02-15 13:36 UTC by gurinderu

2023-03-06 11:01 UTC, justprosh commented on crates/builtins-tests/tests/src/builtins_deployer.rs
> +use log_utils::enable_logs;
```suggestion
```

2023-03-06 11:02 UTC, justprosh commented on crates/builtins-tests/tests/src/builtins_deployer.rs
> +    enable_logs();
```suggestion
```

2023-03-06 11:02 UTC, justprosh commented on crates/builtins-tests/tests/src/builtins_deployer.rs
> +    enable_logs();
```suggestion
```

2023-03-06 11:02 UTC, justprosh commented on crates/particle-node-tests/tests/network/loop_topology.rs
>      // enable_logs();
```suggestion
```

2023-03-06 11:02 UTC, justprosh commented on crates/particle-node-tests/tests/spells.rs
> +use log_utils::enable_logs;
```suggestion
```

2023-03-06 11:03 UTC, justprosh commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
```suggestion
```

2023-03-06 11:03 UTC, justprosh commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
```suggestion
```

2023-03-06 11:03 UTC, justprosh commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
```suggestion
```

2023-03-06 11:03 UTC, justprosh commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
```suggestion
```

2023-03-06 11:04 UTC, justprosh commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
```suggestion
```

2023-03-06 11:04 UTC, justprosh commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
```suggestion
```

2023-03-06 11:04 UTC, justprosh commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
```suggestion
```

2023-03-06 11:04 UTC, justprosh commented on particle-node/src/node.rs
> +    use log_utils::enable_logs;
```suggestion
```

2023-03-06 11:04 UTC, justprosh commented on particle-node/src/node.rs
> +        enable_logs();
```suggestion
```

2023-03-06 13:57 UTC, gurinderu commented on crates/builtins-tests/tests/src/builtins_deployer.rs
> +use log_utils::enable_logs;
Done

2023-03-06 13:57 UTC, gurinderu commented on crates/builtins-tests/tests/src/builtins_deployer.rs
> +    enable_logs();
Done

2023-03-06 13:57 UTC, gurinderu commented on crates/builtins-tests/tests/src/builtins_deployer.rs
> +    enable_logs();
Done

2023-03-06 13:57 UTC, gurinderu commented on crates/particle-node-tests/tests/network/loop_topology.rs
>      // enable_logs();
Done

2023-03-06 13:57 UTC, gurinderu commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
Done

2023-03-06 13:57 UTC, gurinderu commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
Done

2023-03-06 13:57 UTC, gurinderu commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
Done

2023-03-06 13:57 UTC, gurinderu commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
Done

2023-03-06 13:57 UTC, gurinderu commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
Done

2023-03-06 13:57 UTC, gurinderu commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
Done

2023-03-06 13:57 UTC, gurinderu commented on crates/particle-node-tests/tests/spells.rs
> +    enable_logs();
Done

2023-03-06 13:58 UTC, gurinderu commented on particle-node/src/node.rs
> +        enable_logs();
Done

2023-03-06 14:00 UTC, gurinderu commented on sorcerer/src/sorcerer.rs
> +use tokio_stream::wrappers::UnboundedReceiverStream;
Done

2023-03-07 15:48 UTC, justprosh requested changes

2023-03-07 15:48 UTC, justprosh commented on particle-builtins/src/builtins.rs
> +            ("kad", "merge") => wrap(self.kad_merge(args.function_args)),
Please revert these formatting changes

2023-03-07 15:48 UTC, justprosh commented on particle-builtins/src/builtins.rs
> +            ("json", "puts_pairs") => binary(args, |obj: JValue, vs: Vec<(String, JValue)>| -> R<JValue, _> { json::puts_from_pairs(obj, vs) }),
ditto

2023-03-07 15:48 UTC, justprosh commented on particle-builtins/src/builtins.rs
> +            result
```suggestion
            function.call(args, particle).await
```

2023-03-07 16:53 UTC, gurinderu commented on particle-builtins/src/builtins.rs
> +            ("kad", "merge") => wrap(self.kad_merge(args.function_args)),
Done

2023-03-07 16:53 UTC, gurinderu commented on particle-builtins/src/builtins.rs
> +            ("json", "puts_pairs") => binary(args, |obj: JValue, vs: Vec<(String, JValue)>| -> R<JValue, _> { json::puts_from_pairs(obj, vs) }),
Done

2023-03-07 16:54 UTC, folex commented on .cargo/config.toml
> +rustflags = ["--cfg", "tokio_unstable"]
Can you provide a #comment on why this is needed?

2023-03-07 16:55 UTC, folex commented on .config/nextest.toml
> +retries = { backoff = "exponential", count = 3, delay = "5s", jitter = true }
nice

2023-03-07 16:55 UTC, folex commented on .github/workflows/snapshot.yml
> +          RUSTFLAGS: "--cfg tokio_unstable"
isn't `.cargo/config.toml` enough?

2023-03-07 16:55 UTC, folex commented on .github/workflows/tests.yml
> +          RUSTFLAGS: "--cfg tokio_unstable"
ditto

2023-03-07 16:55 UTC, folex commented on .github/workflows/tests.yml
> +          RUSTFLAGS: "--cfg tokio_unstable"
ditto

2023-03-07 16:56 UTC, folex commented on Cargo.toml
> -    "crates/ctrlc-adapter",
awesome! it was a very bad thing. Eager to learn how you replaced it.

2023-03-07 16:56 UTC, gurinderu commented on .cargo/config.toml
> +rustflags = ["--cfg", "tokio_unstable"]
Done

2023-03-07 16:57 UTC, folex commented on aquamarine/src/aqua_runtime.rs
> +        async { task.await.expect("Could not join task") }.boxed()
```suggestion
        async { task.await.expect("Could not join 'Create AVM' task") }.boxed()
```

2023-03-07 16:58 UTC, gurinderu commented on .github/workflows/snapshot.yml
> +          RUSTFLAGS: "--cfg tokio_unstable"
no, unfortunately, cargo installed with toolchain doesn't use it

2023-03-07 16:59 UTC, folex commented on aquamarine/src/aquamarine.rs
> +            .expect("Could not spawn task");
```suggestion
            .expect("Could not spawn 'AVM' task");
```

2023-03-07 16:59 UTC, gurinderu commented on Cargo.toml
> -    "crates/ctrlc-adapter",
was replaced with https://docs.rs/tokio/latest/tokio/signal/fn.ctrl_c.html

2023-03-07 17:01 UTC, gurinderu commented on aquamarine/src/aquamarine.rs
> +    inlet: mpsc::Receiver<Command>,
yes, types.rs was dropped. )

2023-03-07 17:01 UTC, folex commented on aquamarine/src/aquamarine.rs
> +    inlet: mpsc::Receiver<Command>,
Why move from backpressured channel to unbounded one? That makes no sense to me. Sounds dangerous. 

Ideally, everything should be backrpressured. But we don't know how to implement backpressure for libp2p networking, so we kept _everything_ backpressured except at the ConnectionPool edge.

2023-03-07 17:01 UTC, folex commented on aquamarine/src/aquamarine.rs
> +            let sent = self.out.send(effects);
no good...

2023-03-07 17:02 UTC, folex commented on aquamarine/src/aquamarine.rs
> +    outlet: mpsc::Sender<Command>,
ditto. I don't think this is a good idea.

2023-03-07 17:04 UTC, gurinderu commented on aquamarine/src/aqua_runtime.rs
> +        async { task.await.expect("Could not join task") }.boxed()
Done

2023-03-07 17:07 UTC, folex commented on aquamarine/src/particle_executor.rs
> +        async { task.await.expect("Could not join task") }.boxed()
1. Having a possible panic on _every_ particle execution sucks a lot. I can understand having panics on startup, but in runtime?
2. What are the exact reasons these two panics can happen?
3. Is it possible to return Result instead of panic here?
4. Is it possible to eliminate these panics completely?
5. Is it possible to make these panics possible only on startup? (ie once) that, and return Result instead of panic, and we will have nice startup design
6. Please add task names to the error. `Could not join task` is undebuggable and unreportable.

I do no except answers to each of the above questions. Just think on how to improve the design in these directions. Thanks.

2023-03-07 17:08 UTC, gurinderu commented on aquamarine/src/aquamarine.rs
> +            let sent = self.out.send(effects);
self.out is an unbounded channel and it doesn't have and unbounded_send method, in tokio it is called send

2023-03-07 17:09 UTC, gurinderu commented on aquamarine/src/aquamarine.rs
> +    outlet: mpsc::Sender<Command>,
Same story, it was the mpsc::Sender

2023-03-07 17:10 UTC, gurinderu commented on aquamarine/src/aqua_runtime.rs
> +            .expect("Could not spawn task");
Done

2023-03-07 17:11 UTC, folex commented on aquamarine/src/particle_functions.rs
> +    particle_function: Option<Arc<tokio::sync::Mutex<ServiceFunction>>>,
I wonder what price we will pay for that change...

Well anyway we should use queues here instead

2023-03-07 17:12 UTC, folex commented on aquamarine/src/particle_functions.rs
> +            .expect("Could not spawn task");
panicking and crashing the whole rust-peer on every function call is a no go :( what are the alternatives?

2023-03-07 17:14 UTC, folex commented on .github/workflows/snapshot.yml
> +          RUSTFLAGS: "--cfg tokio_unstable"
ehm, what other cargos are there? I never seen any other.

2023-03-07 17:16 UTC, folex commented on aquamarine/src/aquamarine.rs
> +    inlet: mpsc::Receiver<Command>,
Can you keep `BackPressuredInlet` naming please? it is hard to keep in mind, which one is backpressured otherwise

2023-03-07 17:16 UTC, folex commented on aquamarine/src/aquamarine.rs
> +    inlet: mpsc::Receiver<Command>,
well... okay then, let's try

2023-03-07 17:20 UTC, gurinderu commented on aquamarine/src/particle_executor.rs
> +        async { task.await.expect("Could not join task") }.boxed()
1. First expect is a critical error, probably we don't need to return it as a result. For the second expect it is probably better to return a Result instead.
2. First dies if it runs out of tokio runtime, and second dies if the task is cancelled
3. for the second one - yes, if we want to understand that task was cancelled, for the first it is not needed because of a critical error
4. answered
5. answered
6. done

2023-03-07 17:22 UTC, folex commented on aquamarine/src/aquamarine.rs
> +            let sent = self.out.send(effects);
ok

2023-03-07 17:22 UTC, gurinderu commented on aquamarine/src/particle_functions.rs
> +            .expect("Could not spawn task");
it is ok, answered in the previous comment

2023-03-07 17:22 UTC, folex commented on aquamarine/src/aquamarine.rs
> +    outlet: mpsc::Sender<Command>,
good

2023-03-07 17:23 UTC, folex commented on aquamarine/src/particle_executor.rs
> +        async { task.await.expect("Could not join 'Particle' task") }.boxed()
particle id?

and no way we can keep these panics. Can you at least just log the error and then ignore?

2023-03-07 18:26 UTC, folex reviewed
let's use `mpsc::` everywhere, and never import `mpsc::*`

2023-03-07 18:27 UTC, folex commented on aquamarine/src/aquamarine.rs
> +use tokio::sync::mpsc::UnboundedSender;
do not import `UnboundedSender`, use `mpsc::UnboundedSender` in the place instead

2023-03-07 18:27 UTC, folex commented on aquamarine/src/aquamarine.rs
>  use futures::{channel::mpsc, SinkExt, StreamExt};
let's move from channels of futures utils to tokio mpsc

2023-03-08 08:45 UTC, kmd-fl commented on aquamarine/src/plumber.rs
> +        task::Builder::new()
I wonder if it's possible to reduce the number of symbols in this `task::Builder::new().name().spawn().expect()` flow somehow. With a macro or something. I think it's too much distracting text.

2023-03-08 14:38 UTC, gurinderu commented on aquamarine/src/aquamarine.rs
> +    inlet: mpsc::Receiver<Command>,
Done

2023-03-08 14:39 UTC, gurinderu commented on aquamarine/src/particle_functions.rs
> +    particle_function: Option<Arc<tokio::sync::Mutex<ServiceFunction>>>,
yep, it is not free, but it is not critical in this place and it allows us to use tokio-console)

2023-03-09 08:58 UTC, gurinderu commented on aquamarine/src/aquamarine.rs
> +use tokio::sync::mpsc::UnboundedSender;
Done

2023-03-09 08:58 UTC, gurinderu commented on aquamarine/src/aquamarine.rs
>  use futures::{channel::mpsc, SinkExt, StreamExt};
Done

2023-03-09 09:00 UTC, gurinderu commented on aquamarine/src/plumber.rs
> +        task::Builder::new()
Nope,  unfortunately, haven't found any alternatives.

2023-03-15 10:19 UTC, justprosh approved these changes

2023-03-15 11:11 UTC, gurinderu commented on .config/nextest.toml
> +retries = { backoff = "exponential", count = 3, delay = "5s", jitter = true }
failed in this branch? or before? 
A lot of things were fixed in this branch, try to run it for now

2023-03-15 11:40 UTC, folex approved these changes

2023-03-15 11:53 UTC, merged